services:
 
  mongo_db:
    image: mongo:7.0
    container_name: link_shortener_mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    networks:
      - linked_network

  redis:
    image: redis:latest
    container_name: link_shortener_redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - linked_network

volumes:
  mongo_data:
    driver: local

networks:
  linked_network:
    driver: bridge